# Generated by Django 6.0.5 on 2026-05-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('texte', models.TextField()),
                ('couleur_fond', models.CharField(default='#FFFFFF', max_length=7)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
